### ISSUE TITLE
Landing in Django 4.1?

### ISSUE THREAD

**Issue by thinkwelltwd** [dvarrazzo/django-psycopg3-backend#6]
Thank you for psycopg3!! 

I'm looking forward to using it in Django; the feature freeze for Django 4.1 is May 17. Were you planning to get [ticket 33308](https://code.djangoproject.com/ticket/33308) completed / closed by then?

**Comment by dvarrazzo** [comment]
Hello,

I am not actively working with the Django developers: I wrote the driver and the first iteration of the backend but I left the ball in their field. I give them feedback when they ask, but I'm not doing more than this.

You should hear from the Django project about their plans.

**Comment by bjnabs** [comment]
It seems like django has yet to integrate psycopg3 into 4.1. I tried this solution and had issues with the line from django.db.utils inport Text in the base.py. I declares class Text among those in utils.py of django.db. Although it worked, I could not query the database objects, error  being objects do not have conn.status attribute. I am running python 3.11.0 environment

**Comment by dvarrazzo** [comment]
@bjnabs: see reply above. Please get in touch with the Django people to know where things are.

**Comment by pauloxnet** [comment]
I hope a psycopg version 3 backend will be available in Django 4.2.

Some PRs have been already merged in the Django main branch.

This is the main PR you can follow and contribute to if you want to help:
https://github.com/django/django/pull/15687

**Comment by dvarrazzo** [comment]
Thank you for linking the Django MR, @pauloxnet :slightly_smiling_face: 

Closing this, as the state of work is in https://github.com/django/django/pull/15687.

:purple_heart:
